### ISSUE TITLE
Docker Upgrade Script?

### ISSUE THREAD

**Issue by agruen** [marcelbrueckner/paperless.sh#1]
Hi @marcelbrueckner --

I put together this [upgrade script](https://github.com/agruen/Working-Papers/blob/main/Paperless-ngx/docker-compose-upgrade.sh) (which is, for my uses anyway, very nice!).  Would love to give it to you for inclusion here or in the paperless project, if it would be useful to others.

Andrew

**Comment by marcelbrueckner** [comment]
Hey @agruen, thank you very much for your contribution.

You are welcome to create a PR. Or, if you prefer, I can add it myself.
