### ISSUE TITLE
Are you interested in  a little python script which downloads all JSON via API ?

### ISSUE THREAD

**Issue by nklamann** [marcelbrueckner/paperless.sh#9]
I played around and got this here working; https://gist.github.com/nklamann/02dbf4d4a6add63ea67ec838aa9f7e84. 

The python scripts loads only one page of data by default, but this can be changed trivially with a constant.

**Comment by marcelbrueckner** [comment]
Yes. I can imagine that this could be very handy for some people. If you don't mind, I would like to use your code as inspiration to integrate this functionality into my [Paperless-ngx CLI](https://github.com/marcelbrueckner/paperless-ngx-cli) at some point.

**Comment by nklamann** [comment]
That is fine by me.
